### PR TITLE
Decom deprecated/migrated test repo

### PR DESCRIPTION
**Pull request by stephendonner**
@glogiotatidis / @davehunt r?

This partially addresses https://github.com/mozilla/snippets-tests/issues/95, and I'll take care of the rest, accordingly, as well.

### CODE REVIEW

**Comment by davehunt** [comment]
Has Jenkins been updated to use the main repository? We should also add snippets-service to Treeherder and update the Treeherder submission to the new repo name, otherwise revisions will not match up. See http://treeherder.readthedocs.io/submitting_data.html#add-github-repo and https://bugzilla.mozilla.org/show_bug.cgi?id=1351644 for more details.

**Comment by stephendonner** [comment]
Thanks for the prod/reminder, Dave:

1) Updated the snippets.stage job for the main repo in https://fx-test-jenkins.stage.mozaws.net/job/snippets.stage/jobConfigHistory/showDiffFiles?timestamp1=2017-02-22_23-03-01&timestamp2=2017-06-25_07-19-48
2) Likewise, updated snippets.prod in https://fx-test-jenkins.stage.mozaws.net/job/snippets.prod/jobConfigHistory/showDiffFiles?timestamp1=2017-02-22_23-13-26&timestamp2=2017-06-25_07-22-39
3) PR up for changing metadata in https://github.com/mozilla/treeherder/pull/2594
4) Bug filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1376166

**Comment by davehunt** [comment]
I've also updated snippets.adhoc on fx-test-jenkins-dev.

**Comment by stephendonner** [comment]
Thanks, @davehunt - I had created https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/snippets-service/ as the test/ad-hoc job for this PR, but it's better to modify the existing one, as you have.

**Comment by stephendonner** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1377843 for the request to install/configure Taskcluster integration into GitHub, via a hook.

**Pull request merged**
